### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6 עוקב אחר מדיניות מחזור-חיים קבועה.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Windows Desktops,Sequencer
  ms.openlocfilehash: e7ee52090b6e77209d2cc75b5862c21dfe4fe3dd
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: he-IL
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935561"
name: Microsoft Application Virtualization 4.6
summary: >+
  Microsoft Application Virtualization 4.6 עוקב אחר מדיניות מחזור-חיים [קבועה](/lifecycle/policies/fixed).


  דבר זה חל על המהדורות הבאות: for Remote Desktop Services, עבור Windows Desktops, Sequencer

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>קישורים \n* [מידע אודות המוצר ומעבר](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [הדרכת ביצוע מעבר](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [מדיניות חבילת תמיכה](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> מאחר ומשתמשי App-V 4.6 משתמשים ב- App-V 4.5 Server, ה- App-V 4.5 Server ימשיך להיתמך בהתאם לתאריכי מחזור-חיים של App-V 4.6 בעת שימוש עם לקוח ה- App-V 4.6 הנתמך.\n\n## <a name=\"editions\"></a>מהדורות \n* עבור Remote Desktop Services\n* for Windows Desktops\n* Sequencer"
