### YamlMime:Lifecycle
metadata:
  title: מנהל תצורה של מרכז המערכת של Microsoft 2012
  description: מנהל התצורה של מרכז המערכת של Microsoft  2012 עוקב אחר מדיניות מחזור החיים הקבועה.
  ms.date: 03/12/2021
  keywords: null
name: מנהל תצורה של מרכז המערכת של Microsoft 2012
summary: |+
  מנהל התצורה של מרכז המערכת של Microsoft 2012 עוקב אחר מדיניות מחזור החיים [הקבועה.](/lifecycle/policies/fixed)


products:
  - msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
  - version: Service Pack 2
    startDate: 05/12/2015
    endDate: 07/12/2022
  - version: Service Pack 1
    startDate: 12/15/2012
    endDate: 07/12/2016
  - version: Original Release
    startDate: 05/30/2012
    endDate: 01/14/2014
content: |+

  ## <a name="links"></a>קישורים 
  * [מדיניות חבילת תמיכה](/lifecycle/policies/fixed#service-packs)
  * [תיעוד מרכז המערכת](/system-center/#pivot=components&panel=components-all)
  * [משאבי מרכז המערכת](https://www.microsoft.com/system-center/resources)
  * [הדרכת ביצוע מעבר](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)