### YamlMime:Lifecycle
metadata:
  title: מנהל התצורה של מרכז המערכת של Microsoft 2007
  description: מנהל התצורה של מרכז המערכת של Microsoft 2007 עוקב אחר מדיניות מחזור חיי הקבוע.
  ms.date: 07/28/2020
  ms.openlocfilehash: 796670fd93547cc79f69c544085070efb0116650
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: he-IL
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "819757"
name: מנהל התצורה של מרכז המערכת של Microsoft 2007
summary: >
  מנהל התצורה של מרכז המערכת של Microsoft 2007 עוקב אחר מדיניות מחזור חיי [הקבוע](/lifecycle/policies/fixed) .



  > [!IMPORTANT]

  > התמיכה במוצר זה הסתיימה. ראה הנחיות הגירה להלן.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Service Pack 2
  startDate: 10/22/2009
  endDate: 07/09/2019
- version: Service Pack 1
  startDate: 05/21/2008
  endDate: 01/11/2011
- version: Original Release
  startDate: 11/29/2007
  endDate: 07/14/2009
content: "\n## <a name=\"links\"></a>קישורים \n* [הנחיית הגירה](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [מידע אודות המוצר](/mem/configmgr/core/understand/introduction)\n* [מדיניות חבילת שירות](/lifecycle/policies/fixed#service-packs)"
