### YamlMime:Lifecycle
metadata:
  title: אבטחת לקוח של Microsoft Forefront
  description: אבטחת לקוח של Microsoft Forefront עוקבת אחר מדיניות מחזור חיי הקבוע.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: he-IL
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924256"
name: אבטחת לקוח של Microsoft Forefront
summary: >+
  אבטחת לקוח של Microsoft Forefront עוקבת אחר מדיניות מחזור חיי [הקבוע](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>קישורים \n* [הגנה על נקודות קצה של מרכז המערכת](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> אבטחת לקוח של הלקוח הופסקה מ-14 ביולי 2015. עדכוני ההגדרה Antimalware ו-Antispyware לא יהיו זמינים עוד לאחר סוף התמיכה של גירסת המוצר. הערכת הגנה של נקודות קצה של מרכז המערכת כתחליף."
