### YamlMime:Lifecycle
metadata:
  title: אבטחת לקוח של Microsoft Forefront
  description: אבטחת לקוח של Microsoft Forefront עוקבת אחר מדיניות מחזור חיי הקבוע.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: he-IL
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908750"
name: אבטחת לקוח של Microsoft Forefront
summary: >+
  אבטחת לקוח של Microsoft Forefront עוקבת אחר מדיניות מחזור חיי [הקבוע](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>קישורים \n* [הגנה על נקודות קצה של מרכז המערכת](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> אבטחת לקוח של מחשב חנית הופסק. התמיכה מסתיימת ב-14 ביולי 2015. עדכוני ההגדרה Antimalware ו-Antispyware לא יהיו זמינים עוד לאחר סוף התמיכה של גירסת המוצר. הערכת הגנה של נקודות קצה של מרכז המערכת כתחליף."
