### YamlMime:Lifecycle
metadata:
  title: מנהל התצורה של מרכז המערכת של Microsoft 2007 R2
  description: מנהל התצורה של מרכז המערכת של Microsoft 2007 R2 עוקב אחר מדיניות מחזור החיים הקבוע.
  ms.date: 07/28/2020
  ms.openlocfilehash: 0da71b9a2886e1a7012339ebef9a5fbe64f8811e
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: he-IL
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "819758"
name: מנהל התצורה של מרכז המערכת של Microsoft 2007 R2
summary: >
  מנהל התצורה של מרכז המערכת של Microsoft 2007 R2 עוקב אחר מדיניות מחזור החיים [הקבוע](/lifecycle/policies/fixed) .



  > [!IMPORTANT]

  > התמיכה במוצר זה הסתיימה. ראה הנחיות הגירה להלן.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>קישורים \n* [הנחיית הגירה](/mem/configmgr/core/migration/planning-for-migration)\n* [הנחיית הגירה נוספת](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
